// DO NOT EDIT. This is code generated via package:easy_localization/generate.dart

// ignore_for_file: prefer_single_quotes, avoid_renaming_method_parameters, constant_identifier_names

import 'dart:ui';

import 'package:easy_localization/easy_localization.dart' show AssetLoader;

class CodegenLoader extends AssetLoader{
  const CodegenLoader();

  @override
  Future<Map<String, dynamic>?> load(String path, Locale locale) {
    return Future.value(mapLocales[locale.toString()]);
  }

  static const Map<String,dynamic> _ar = {
  "appName": "باي ظبط",
  "tagline": "تابع مصروفاتك وابقَ مسيطراً",
  "welcomeTitle": "مرحبًا بك في باي ظبط",
  "welcomeSubtitle": "لنُسهّل عليك متابعة أموالك.",
  "exploreApp": "استكشف التطبيق",
  "signIn": "تسجيل الدخول",
  "createAccount": "إنشاء حساب",
  "forgotPassword": "نسيت كلمة المرور؟",
  "createNewAccount": "إنشاء حساب جديد",
  "repeatPassword": "كرر كلمة المرور",
  "createPassword": "إنشاء كلمة مرور",
  "moneyOrganizedInOnePlace": "أموالك منظمة بوضوح في مكان واحد.",
  "agreeToThe": "أنا اوافق على ",
  "and": " و ",
  "haveAnAccount": "لديك حساب بالفعل؟",
  "signInToContinue": "سجل الدخول لادارة اموالك",
  "resetPassword": "إعادة تعيين كلمة المرور",
  "verifyCode": "تأكيد الرمز",
  "checkEmail": "تحقق من بريدك الإلكتروني",
  "trackYourSpend": "تابع ما تنفقه",
  "mustBe8Characters": "يجب ان يكون 8 حروف",
  "dontHaveAccount": "ليس لديك حساب؟",
  "trackYourExpenses": "سجل مصروفاتك لترى أين تذهب أموالك.",
  "organizeSpendingWithEnvelopes": "نظم إنفاقك باستخدام المظاريف.",
  "setLimitsForCategories": "حدد حدودًا بسيطة لفئات مثل الطعام أو المواصلات للبقاء على المسار الصحيح.",
  "buildYourSavings": "ابنِ مدخراتك.",
  "saveLeftoverMoney": "احتفظ بالأموال المتبقية لتكوين شبكة أمان لنفسك.",
  "yourGoalsYourProgress": "أهدافك وتقدمك.",
  "createGoalsAndTrackSavings": "أنشئ أهدافًا ووجه مدخراتك نحو ما يهمك.",
  "financeUnderControl": "الآن أموالك في مكان واحد وتحت السيطرة دائمًا.",
  "forgotPasswordMessage": "عذرًا، يحدث ذلك للجميع. أدخل بريدك الإلكتروني لإصلاح المشكلة.",
  "enterFiveDigitCode": "أدخل الرمز المكون من 5 أرقام المذكور في البريد الإلكتروني.",
  "resetLinkSent": "لقد أرسلنا رابط إعادة التعيين إلى alpha...@gmail.com",
  "createYourAccount": "أنشئ حسابك",
  "welcomeBack": "مرحبًا بعودتك",
  "agreeToTerms": "أوافق على شروط الخدمة وسياسة الخصوصية",
  "fullName": "الاسم الكامل",
  "email": "البريد الإلكتروني",
  "password": "كلمة المرور",
  "confirmPassword": "تأكيد كلمة المرور",
  "logout": "تسجيل الخروج",
  "logoutConfirmation": "هل أنت متأكد أنك تريد تسجيل الخروج؟ بياناتك محفوظة محليًا وستكون موجودة عند عودتك.",
  "monthlyIncome": "الدخل الشهري",
  "whatIsYourMonthlyIncome": "ما هو دخلك الشهري؟",
  "incomeTip": "أضف جميع مصادر الدخل مثل الراتب أو العمل الحر أو أي دخل إضافي.",
  "addIncome": "إضافة دخل",
  "editIncome": "تعديل الدخل",
  "income": "الدخل",
  "monthlyBudget": "الميزانية الشهرية",
  "setMonthlyBudget": "حدد ميزانيتك الشهرية",
  "budgetTip": "يفضل أن تكون الميزانية أقل من الدخل لتتمكن من الادخار.",
  "budgetHigherThanIncome": "⚠️ ميزانيتك أعلى من دخلك",
  "budgetUsed": "الميزانية المستخدمة",
  "overBudget": "تجاوزت الميزانية",
  "carryItForward": "ترحيل الفائض",
  "startFresh": "ابدأ من جديد",
  "recommended": "مقترح",
  "budgetCycleDate": "تاريخ دورة الميزانية",
  "monthlyBudgetResets": "إعادة تعيين الميزانية الشهرية",
  "selectDayOfMonth": "اختر يومًا من الشهر",
  "changeBudgetCycleDate": "تغيير تاريخ دورة الميزانية",
  "rolloverComplete": "تم ترحيل الميزانية!",
  "nextMonthsBoost": "تعزيز للشهر القادم",
  "addTransactions": "إضافة معاملات",
  "addExpense": "إضافة مصروف",
  "editTransaction": "تعديل المعاملة",
  "deleteTransaction": "حذف المعاملة",
  "transactionDeleted": "تم حذف المعاملة",
  "recordMoneyIn": "سجل الأموال التي دخلت.",
  "recordMoneyOut": "سجل أين ذهبت أموالك.",
  "searchTransactions": "ابحث في المعاملات...",
  "expenses": "المصروفات",
  "title": "العنوان",
  "amount": "المبلغ",
  "category": "التصنيف",
  "paymentMethod": "طريقة الدفع",
  "note": "ملاحظة",
  "repeatEveryMonth": "يتكرر كل شهر",
  "repeatDescription": "سيتم إضافته تلقائيًا كل شهر.",
  "deleteTransactionConfirmation": "هل أنت متأكد أنك تريد حذف هذه المعاملة؟",
  "food": "طعام",
  "fuel": "وقود",
  "health": "صحة",
  "bills": "فواتير",
  "transportation": "مواصلات",
  "grocery": "بقالة",
  "rent": "إيجار",
  "entertainment": "ترفيه",
  "investment": "استثمار",
  "travel": "سفر",
  "gifts": "هدايا",
  "shopping": "تسوق",
  "gym": "جيم",
  "salary": "راتب",
  "applePay": "آبل باي",
  "home": "الرئيسية",
  "others": "أخرى",
  "addNewCategory": "إضافة تصنيف جديد",
  "searchCategories": "ابحث في التصنيفات",
  "createNewCategory": "إنشاء تصنيف جديد",
  "categoryName": "اسم التصنيف",
  "envelopes": "المظاريف",
  "setLimits": "حدد حدودًا لتنظيم إنفاقك.",
  "createEnvelope": "إنشاء ظرف",
  "editEnvelope": "تعديل الظرف",
  "deleteEnvelope": "حذف الظرف",
  "deleteEnvelopeConfirmation": "هل أنت متأكد أنك تريد حذف هذا الظرف؟ سيتم إرجاع المبلغ إلى إجمالي دخلك.",
  "onTrack": "على المسار",
  "budget": "الميزانية",
  "goals": "الأهداف",
  "trackProgress": "تابع تقدمك نحو أهدافك.",
  "createNewGoal": "إنشاء هدف جديد",
  "goalName": "اسم الهدف",
  "targetAmount": "المبلغ المستهدف (جنيه)",
  "addMoneyToGoal": "إضافة مال",
  "goalProgress": "تقدم الهدف",
  "editGoal": "تعديل الهدف",
  "deleteGoal": "حذف الهدف",
  "goalDeleted": "تم حذف الهدف",
  "deleteGoalConfirmation": "هل أنت متأكد أنك تريد حذف هذا الهدف؟ سيتم إرجاع المبلغ المدخر إلى إجمالي مدخراتك.",
  "totalSavedTowardGoals": "إجمالي المدخرات للأهداف",
  "inProgress": "قيد التنفيذ",
  "completedGoals": "الأهداف المكتملة",
  "totalSavings": "إجمالي المدخرات",
  "savingsHistory": "سجل المدخرات",
  "allocateToGoal": "تخصيص للهدف",
  "editSavings": "تعديل المدخرات",
  "editTotalSavings": "تعديل إجمالي المدخرات",
  "currentSaving": "المدخر الحالي",
  "amountToAllocate": "المبلغ المراد تخصيصه (جنيه)",
  "analyticsReport": "تقرير التحليلات",
  "financialInsights": "رؤيتك المالية",
  "week": "أسبوع",
  "month": "شهر",
  "year": "سنة",
  "totalSpent": "إجمالي المصروف",
  "avgDaily": "المتوسط اليومي",
  "savingRate": "معدل الادخار",
  "incomeVsExpenses": "الدخل مقابل المصروفات",
  "spendingByCategory": "الإنفاق حسب التصنيف",
  "weeklyPattern": "النمط الأسبوعي",
  "exportReport": "تصدير التقرير",
  "downloadPdfReport": "تحميل التقرير PDF",
  "insights": "رؤى",
  "understandingSpendingBehavior": "فهم سلوك الإنفاق الخاص بك",
  "notifications": "الإشعارات",
  "stayInformed": "ابقَ على اطلاع على التحديثات المهمة.",
  "noNotifications": "لا توجد إشعارات",
  "allCaughtUp": "أنت على اطلاع كامل! سنخبرك عند وصول شيء جديد.",
  "budgetLimitWarning": "تحذير حد الميزانية",
  "expenseAdded": "تمت إضافة مصروف",
  "monthStarted": "بدأ الشهر",
  "goalContribution": "مساهمة في الهدف",
  "monthlyRolloverApplied": "تم ترحيل الميزانية الشهرية",
  "manageAccount": "إدارة حسابك وتفضيلاتك",
  "reportsAndInsights": "التقارير والرؤى",
  "exportData": "تصدير البيانات",
  "preferences": "التفضيلات",
  "support": "الدعم",
  "helpCenter": "مركز المساعدة",
  "privacyPolicy": "سياسة الخصوصية",
  "termsOfService": "شروط الخدمة",
  "profileSettings": "إعدادات الملف الشخصي",
  "personalInformation": "المعلومات الشخصية",
  "accountInformation": "معلومات الحساب",
  "memberSince": "عضو منذ",
  "accountStatus": "حالة الحساب",
  "active": "نشط",
  "continue_": "استمرار",
  "cancel": "إلغاء",
  "saveChanges": "حفظ التغييرات",
  "delete": "حذف",
  "confirm": "تأكيد",
  "completeSetup": "إكمال الإعداد",
  "skipForNow": "تخطي الآن",
  "egp": "جنيه",
  "tip": "نصيحة",
  "login": "تسجيل الدخول"
};
static const Map<String,dynamic> _en = {
  "appName": "Payzabt",
  "tagline": "Track expenses. Stay in control",
  "welcomeTitle": "Welcome to Payzabt",
  "welcomeSubtitle": "Let’s make your money easier to follow.",
  "trackYourExpenses": "Record your expenses to see where your money goes.",
  "trackYourSpend": "Track what you spend",
  "mustBe8Characters": "must be 8 characters",
  "dontHaveAccount": "Don't have an account?",
  "signInToContinue": "Sign in to continue managing your money.",
  "organizeSpendingWithEnvelopes": "Organize your spending with envelopes.",
  "setLimitsForCategories": "Set simple limits for categories like food or transport to stay on track.",
  "buildYourSavings": "Build your savings.",
  "saveLeftoverMoney": "Set aside leftover money to create a safety net for yourself.",
  "yourGoalsYourProgress": "Your goals, your progress.",
  "createGoalsAndTrackSavings": "Create goals and move your savings toward what matters to you.",
  "financeUnderControl": "Now your finances are in one place and always under control.",
  "forgotPasswordMessage": "Oops. It happens to the best of us. Input your email address to fix the issue.",
  "enterFiveDigitCode": "Enter the 5 digit code mentioned in the email.",
  "resetLinkSent": "We sent a reset link to alpha...@gmail.com",
  "createYourAccount": "Create your account",
  "exploreApp": "Explore the app",
  "signIn": "Sign In",
  "haveAnAccount": "Already have an account?",
  "createAccount": "Create Account",
  "agreeToThe": "I agree to the ",
  "and": " and ",
  "CreatePassword": "Create a password",
  "forgotPassword": "Forgot Password?",
  "resetPassword": "Reset Password",
  "verifyCode": "Verify Code",
  "checkEmail": "Check your email",
  "welcomeBack": "Welcome Back",
  "fullName": "Full Name",
  "email": "Email",
  "password": "Password",
  "confirmPassword": "Confirm Password",
  "logout": "Log Out",
  "login": "Login",
  "logoutConfirmation": "Are you sure you want to log out? Your data is saved locally and will be here when you return.",
  "monthlyIncome": "Monthly Income",
  "whatIsYourMonthlyIncome": "What is your monthly income?",
  "incomeTip": "Include all sources of income like salary, freelance work, or side hustles.",
  "addIncome": "Add Income",
  "editIncome": "Edit Income",
  "income": "Income",
  "monthlyBudget": "Monthly Budget",
  "setMonthlyBudget": "Set your monthly budget",
  "budgetTip": "Budget should be less than your income to allow for savings.",
  "budgetHigherThanIncome": "⚠️ Your budget is higher than your income",
  "budgetUsed": "Budget Used",
  "overBudget": "Over Budget",
  "carryItForward": "Carry it forward",
  "startFresh": "Start fresh",
  "recommended": "Recommended",
  "budgetCycleDate": "Budget cycle date",
  "monthlyBudgetResets": "Monthly budget resets",
  "selectDayOfMonth": "Select the day of the month",
  "changeBudgetCycleDate": "Change budget cycle date",
  "rolloverComplete": "Rollover Complete!",
  "nextMonthsBoost": "Next Month's Boost",
  "addTransactions": "Add Transactions",
  "addExpense": "Add Expense",
  "editTransaction": "Edit Transaction",
  "deleteTransaction": "Delete Transaction",
  "transactionDeleted": "Transaction deleted",
  "recordMoneyIn": "Record money coming in.",
  "recordMoneyOut": "Record where your money went.",
  "searchTransactions": "Search transactions...",
  "expenses": "Expenses",
  "title": "Title",
  "amount": "Amount",
  "category": "Category",
  "paymentMethod": "Payment method",
  "note": "Note",
  "repeatEveryMonth": "Repeat every month",
  "repeatPassword": "repeat password",
  "repeatDescription": "This will be added automatically every month.",
  "deleteTransactionConfirmation": "Are you sure you want to delete this Transaction?",
  "food": "Food",
  "fuel": "Fuel",
  "health": "Health",
  "bills": "Bills",
  "transportation": "Transportation",
  "grocery": "Grocery",
  "rent": "Rent",
  "entertainment": "Entertainment",
  "investment": "Investment",
  "travel": "Travel",
  "gifts": "Gifts",
  "shopping": "Shopping",
  "gym": "Gym",
  "salary": "Salary",
  "applePay": "Apple Pay",
  "home": "Home",
  "others": "Others",
  "addNewCategory": "Add new category",
  "searchCategories": "Search categories",
  "createNewCategory": "Create New Category",
  "createNewAccount": "Create New Account",
  "moneyOrganizedInOnePlace": "Your money, clearly organized in one place.",
  "categoryName": "Category Name",
  "envelopes": "Envelopes",
  "setLimits": "Set limits to organize your spending.",
  "createEnvelope": "Create Envelope",
  "editEnvelope": "Edit Envelope",
  "deleteEnvelope": "Delete Envelope",
  "deleteEnvelopeConfirmation": "Are you sure you want to delete this Envelope? The Envelope amount will be returned to your total Income.",
  "onTrack": "On-Track",
  "budget": "Budget",
  "goals": "Goals",
  "trackProgress": "Track your progress toward your goals.",
  "createNewGoal": "Create new goal",
  "goalName": "Goal Name",
  "targetAmount": "Target Amount (EGP)",
  "addMoneyToGoal": "Add money",
  "goalProgress": "Goal Progress",
  "editGoal": "Edit Goal",
  "deleteGoal": "Delete Goal",
  "goalDeleted": "Goal deleted",
  "deleteGoalConfirmation": "Are you sure you want to delete this goal? The saved amount will be returned to your total savings.",
  "totalSavedTowardGoals": "Total saved toward goals",
  "inProgress": "In Progress",
  "completedGoals": "Completed Goals",
  "totalSavings": "Total Savings",
  "savingsHistory": "Savings History",
  "allocateToGoal": "Allocate to goal",
  "editSavings": "Edit Savings",
  "editTotalSavings": "Edit Total Savings",
  "currentSaving": "Current Saving",
  "amountToAllocate": "Amount to Allocate (EGP)",
  "analyticsReport": "Analytics Report",
  "financialInsights": "Your financial insights",
  "week": "Week",
  "month": "Month",
  "year": "Year",
  "totalSpent": "Total spent",
  "avgDaily": "Avg Daily",
  "savingRate": "Saving Rate",
  "incomeVsExpenses": "Income vs Expenses",
  "spendingByCategory": "Spending by Category",
  "weeklyPattern": "Weekly Pattern",
  "exportReport": "Export Report",
  "downloadPdfReport": "Download PDF Report",
  "insights": "Insights",
  "understandingSpendingBehavior": "Understanding your spending behavior",
  "notifications": "Notifications",
  "stayInformed": "Stay informed about important updates.",
  "noNotifications": "No Notifications",
  "allCaughtUp": "You're all caught up! We'll notify you when something new arrives.",
  "budgetLimitWarning": "Budget Limit Warning",
  "expenseAdded": "Expense Added",
  "monthStarted": "Month Started",
  "goalContribution": "Goal Contribution",
  "monthlyRolloverApplied": "Monthly Rollover Applied",
  "manageAccount": "Manage your account and preferences",
  "reportsAndInsights": "Reports & Insights",
  "exportData": "Export Data",
  "preferences": "Preferences",
  "support": "Support",
  "helpCenter": "Help Center",
  "privacyPolicy": "Privacy Policy",
  "termsOfService": "Terms of Service",
  "profileSettings": "Profile Settings",
  "personalInformation": "Personal Information",
  "accountInformation": "Account Information",
  "memberSince": "Member Since",
  "accountStatus": "Account Status",
  "active": "Active",
  "continue_": "Continue",
  "cancel": "Cancel",
  "saveChanges": "Save Changes",
  "delete": "Delete",
  "confirm": "Confirm",
  "completeSetup": "Complete Setup",
  "skipForNow": "Skip for now",
  "egp": "EGP",
  "tip": "Tip"
};
static const Map<String, Map<String,dynamic>> mapLocales = {"ar": _ar, "en": _en};
}
