
default_platform(:android)

# To run the lane, execute the following command:
# bundle exec fastlane firebase_distribution

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor prod --target lib/main_prod.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:156052898802:android:2f5672f9faab8b62d3616b",
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-prod-release.apk",
        testers: ENV["EMAIL_ADDRESS"],
        release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
  )
  end
end